//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBuild.Assessment6_WebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameOfThronesCharacter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameOfThronesCharacter()
        {
            this.Guests = new HashSet<Guest>();
        }
    
        public int CharacterID { get; set; }
        public string Name { get; set; }
        public string Aliases { get; set; }
        public string Titles { get; set; }
        public string Mother { get; set; }
        public string Father { get; set; }
        public string Gender { get; set; }
        public string Culture { get; set; }
        public string House { get; set; }
        public string Allegiance { get; set; }
        public string Book { get; set; }
        public string Url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guests { get; set; }
    }
}
