//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace DevBuild.Assessment6_WebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int GuestID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a First Name")]
        public string FirstName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a Last Name")]
        public string LastName { get; set; }
        [DisplayFormat(DataFormatString = "{0:M/d}")]
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public bool IsAttending { get; set; } = false;
        public bool HasAPlusOne { get; set; } = false;

        [Required, EmailAddress, MaxLength(50)]
        public string EmailAddress { get; set; }
        public string Guest1 { get; set; }
    }
}
