//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBuild.Assessment6_WebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest1
    {
        public int GuestID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsAttending { get; set; }
        public Nullable<bool> HasAPlusOne { get; set; }
        public string Guest11 { get; set; }
        public Nullable<bool> BringingADish { get; set; }
        public Nullable<int> DishID { get; set; }
    }
}
